### ISSUE TITLE
No Chromecast controls when casting from phone

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/elections14#1304]

**Comment by TylerFisher** [comment]
Looks like a JS error of some kind.

**Comment by TylerFisher** [comment]
It gets weirder: this doesn't work on my iPhone 5S, works on Christina's 4S

**Comment by onyxfish** [comment]
Sooooo... this looks like a regression in the Chrome release for iOS 8. On that specific version, the session listener callback is never fired, so we have no way of knowing that that the session has begun. We can't simply call up the controls when the button is clicked, because there might not be a device available. I don't see any way of working around this. We should decide if we want to simply hide the button on mobile.

**Comment by onyxfish** [comment]
Superseded by #1343.
