### ISSUE TITLE
Verify we don't care about runoff calls on election night

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#416]
Doesn't seem like this can happen in the timeframe we care about?

**Comment by eads** [comment]
Actually, there is one scenario where we do care because of Lousiana's goofy system. Charlie explained to me that LA's election is actually a kind of hybrid primary -- if a candidate wins more than 50% for a seat, they simply win. But if no candidate exceeds 50%, the race goes to a runoff in December between the two highest vote-getters. It applies to house and senate, but we aren't currently featuring any LA house races.

**Comment by eads** [comment]
There's a significant chance the LA senate race ends in a runoff. Plus we might need call cards for LA runoffs in house races. We care! Damn you, [Jungle Primary](http://en.wikipedia.org/wiki/Nonpartisan_blanket_primary#Louisiana_Open_Primary)!
