### ISSUE TITLE
Prototype AP data cron job

### ISSUE THREAD

**Issue by onyxfish** [nprapps/elections14#57]

**Comment by eads** [comment]
I'm curious about something with this based on my experience with the Reuters API and understanding of what AP is going for with the new API. Here's how it has worked for the last few Tribune elections:
- We accessed the Reuters API with a pure Javascript client -- no server side python processing.
- Reporter-supplied data input in Google spreadsheets was massaged into the Reuters format so that one client could work with all of it.
- To handle failover the JS client polled to receive the data file location -- all our cron job did was cache the Reuters data on S3. If their service went down, we could update the file location to tell clients to use the backup copy until the API came back up.

Are we working off the assumption we need to process and proxy the AP data on our own rig? Is that a good assumption?

**Comment by onyxfish** [comment]
I think it depends on the verbosity and convenience of the AP data format. If the API calls give us everything we need in the minimum number of bytes them I'm all for proxying, but I suspect that if it's like the last time, we'll want to thin out and restructure the data a bit before hand it off to the JS...
